fix: mammoth.js requires 'buffer' not 'arrayBuffer' in Deno
Error: Could not find file in options
Fix: Use { buffer: new Uint8Array(buffer) } instead of { arrayBuffer: buffer }
Reference: https://blog.gitcode.com/1271379e1138cfb1df0e64af9814ac3d.html